### ISSUE TITLE
Where is index.html?

### ISSUE THREAD

**Issue by oUp2Uo** [JohannesKrueger/pointcloudeditor#1]
Thanks for the great work.

I have pulled this project, but could not find `index.html`, only `index.php` which cannot be opened by the browser.

Thank you.

**Comment by JohannesKrueger** [comment]
I accidentally saved the index file from my host (.php) when transferring. I have now updated the code with a working .html file. Thanks for the issue message!

**Comment by oUp2Uo** [comment]
Thanks for the reply, It works now!

And I have some small question about `Erase Mode`.
It is a bit hard to understand now.
Does it means the red points will be deleted when export the result?
And how to cancel the selected points?

Thank you.

**Comment by JohannesKrueger** [comment]
Hello, I'm glad to hear that. 

Erase mode works like this: It shoots a ray through the point cloud and all nearby points are colored red. 

These red dots are ignored during downloading and are therefore deleted.

Unfortunately, I haven't had the time yet to find a way to undo colored points.

**Comment by oUp2Uo** [comment]
Hi, thanks for the reply.

The rotation and translation function is really good.

Erase mode now is not easy using, since mis-click will often occur when the point cloud is large.
Maybe just mark the last selection and add an undo button which is used to undo last selection is an easy way.
Or just setting an undo mode to select the red points and clear them?

**Comment by JohannesKrueger** [comment]
Thanks for the tip, unfortunately the Pointclound editor is not yet completely user-friendly and I have a lot to do at the moment, so I can't improve it any further at the moment.

I will soon take care of implementing a few more features and making the editor user-friendly

**Comment by oUp2Uo** [comment]
Please take you time.
Now it is enough a good tool for processing point cloud. 
: )
