### ISSUE TITLE
Some feature points coordinates became undefined after translation/rotation.

### ISSUE THREAD

**Issue by oUp2Uo** [JohannesKrueger/pointcloudeditor#2]
Hi,

I found some feature points coordinates became undefined after translation/rotation.

Please see the attatched files.

The feature points data of last two pictures was missed and became `undefined`.
Meanwhile, I thought the poses of cameras were calculated correctly.

And there were 4 more `undefined` at the end of the file.

[images.txt](https://github.com/user-attachments/files/16796279/images.txt)

[modifiedImages.txt](https://github.com/user-attachments/files/16796280/modifiedImages.txt)

Thank you.

**Comment by JohannesKrueger** [comment]
Thank you for the error message and for providing the files. I was able to reconstruct the error. It seems to be related to the function that reads the images.txt. I will take care of the error correction and will let you know as soon as it is resolved.

**Comment by JohannesKrueger** [comment]
I found the error and fixed it. When reading the Images.txt there was a 0.5% chance that a camera was read incorrectly or declared as "undefined". I fixed the error with the improved const imageRegex = /^\d+ .*?\.(jpg|png)\s*$/; in the processImages function.

**Comment by oUp2Uo** [comment]
Thanks for the quick reply!

I tried some pointclouds, and it seems that no `undefined` now.
